### PR TITLE
allowing custom Brewfile path in the argument

### PR DESCRIPTION
**Pull request by xu-cheng**
It can be useful if there're multiple Brewfile configurations.
e.g.

    brew brewdle --file=Brewfile.osx
    brew brewdle --file=Brewfile.linux

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Seems good to me. I almost wonder if we want to allow a "system" `Brewfile` somehow? That `brew cleanup-installed` command I've not deprecated has the advantage that you don't need to specify a full path to a `Brewfile` (but I don't think that's a big deal). What do you think?

**Comment by xu-cheng** [comment]
I'm basically fine with a system `Brewfile`. Although I think it's a little risk to read a remote file, should we add an argument to enable it? Like `brew brewdle cleanup --system` or something. And use `brew brewdle dump --system` to dump into it?

Maybe ping @andrew for his opinion.

**Comment by mikemcquaid** [comment]
Yeh `--system` makes sense.

**Comment by xu-cheng** [comment]
Updated.

**Comment by mikemcquaid** [comment]
Looks great! Sorry to contradict myself but I think I meant `--global` rather than `--system` to match what Git does: `--local` (which is implied), `--global` for your `$HOME`, `--system` for `/etc` and specifying files directly

**Comment by xu-cheng** [comment]
No problem. Updated to use `--global`. Also, I switch to use `$HOME/.Brewfile` rather than `~/.Brewfile`.

**Comment by mikemcquaid** [comment]
:+1: :shipit:

**Pull request merged**
